config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "guests#index"
  resources :guests, only: [:index, :show]
  resources :episodes, only: [:index, :show]
  resources :appearances, only: [:new, :create, :edit, :show, :update]

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'

end

app/models/appearance.rb
class Appearance < ApplicationRecord
  validates :rating, :inclusion => 1..5
  validates :guest_id, :uniqueness => {:scope => :episode_id}
  
  belongs_to :guest
  belongs_to :episode
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  has_many :appearances
  has_many :guests, through: :appearances
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_many :appearances
  has_many :episodes, through: :appearances

  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many:appearances
end

app/controllers/appearances_controller.rb
class AppearancesController < ApplicationController
  before_action :require_login, only: [:new, :edit, :create, :update,]

  def new
    @appearance = Appearance.new
  end

  def create
    @appearance = Appearance.new(appearance_params)
    if @appearance.save
      redirect_to @appearance.episode
    else
      redirect_to new_appearance_path
    end
  end
  
  def show 
    @appearance = Appearance.find(params[:id])
    redirect_to @appearance.episode
  end
  
  def edit 
    @appearance = Appearance.find(params[:id])
  end
 
  def update 
    @appearance = Appearance.find(params[:id])
    if @appearance.update(appearance_params)
      redirect_to @appearance.episode
    else 
      render :edit
    end
  end
 
  private

  def appearance_params
    params.require(:appearance).permit(:guest_id, :episode_id, :user_id, :rating)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def current_user 
  	if logged_in?
  		current_user = User.find(session[:user_id])
  	end
  end

  def logged_in?
  	!!session[:user_id]
  end

  def require_login
  	if !logged_in?
   		redirect_to login_path
  	end
  end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @episodes = Episode.all
  end

  def show
    @episode = Episode.find(params[:id])
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to episodes_path
    else
      redirect_to login_path
    end
  end

end

app/helpers/appearances_helper.rb
module AppearancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user 
		current_user ||= User.where(id:session[:user_id])[0]
	end

end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/appearances/edit.html.erb
<h1>Edit an Appearance</h1>

<%= form_for @appearance do |f| %>
  <%= f.label :rating %>
  <%= f.number_field :rating, in: (1..5) %>
  <%= f.collection_select :episode_id, Episode.all, :id, :date %>
  <%= f.collection_select :guest_id, Guest.all, :id, :name %>
  <% if session[:user_id] %>
  	<%= f.hidden_field :user_id %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/appearances/new.html.erb
<h1>Create an Appearance</h1>

<%= form_for @appearance do |f| %>
  <%= f.label :rating %>
  <%= f.number_field :rating, in: (1..5) %>
  <%= f.collection_select :episode_id, Episode.all, :id, :date %>
  <%= f.collection_select :guest_id, Guest.all, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/episodes/index.html.erb
<h1>All Episodes</h1>

<ul>
  <% @episodes.each do |episode| %>
    <li><%= link_to "Episode #{episode.number} - #{episode.date.strftime("%B %d, %Y")}", episode %></li>
  <% end %>
</ul>

app/views/episodes/show.html.erb
<h1>Episode</h1>

<h3><%= "Date: #{@episode.date}" %></h3>

<h3>Guests</h3>
<ul>
  <% @episode.guests.each do |guest| %>
    <li><%= link_to guest.name, guest %></li>
  <% end %>
</ul>

app/views/guests/index.html.erb
<h1>All The Guests</h1>

<ul>
  <% @guests.each do |guest| %>
    <li><%= link_to guest.name, guest %></li>
  <% end %>
</ul>

app/views/guests/show.html.erb
<h1><%= @guest.name %></h1>

<h3><%= @guest.occupation %></h3>
<% @guest.appearances.each do |a| %>
	<div class="fancystuff">
		<h2>Episode Appearance: <%=  link_to a.episode.date, a.episode %></h2>
		<h3>Episode Rating: <%=  a.rating %></h3>
		<p>Guest Booked By: <%= a.user.username %></p>
		<%= link_to "Edit Appearance", edit_appearance_path(a) %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImmersiveRailsAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= link_to "View All Guests", guests_path %>
    <%= link_to "View All Episodes", episodes_path %>
  </body>
</html>